AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    database-tester

    SAM Template for database-tester


Globals:
    Function:
        Timeout: 30

Resources:

    DatabaseTesterFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: index.handler
            Runtime: nodejs16.x   
            Description: 'function to test database speed'         
            Events:
                DatabaseTesterAPI:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /
                        Method: post



Outputs:

    DatabaseTesterAPI:
      Description: "API Gateway endpoint URL for Prod stage for Database Tester function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

    DatabaseTesterFunction:
      Description: "Database Tester Function ARN"
      Value: !GetAtt DatabaseTesterFunction.Arn